### ISSUE TITLE
Neustaly update opravneni

### ISSUE THREAD

**Issue by hegerj** [topmonks/hlidac-shopu#117]
Poslednich par dni se mi stava ze rozsireni skoro kazdy den pozaduje povoleni pozadovanych opravneni.
Firefox i Chrome; Verze 1.8.1.

**Comment by rarous** [comment]
Hlídač Shopů vyžaduje oprávnění na jednotlivé shopy, které podporuje. V posledních dnech jsme jich přidali poměrně hodně. Chápu, že to může být otravné, ale chceme být transparentní v tom, co děláme a kde. Zároveň consent s přístupem k novým shopům považuji za takový changelog, kdy se rychle dozvíte, jaké shopy přibyly. Nechám tuhle issue otevřenou. Pokud se najde dostatek lidí, kterým transparance vadí, můžeme opravnění změnit na wildcard. 

Wildcard, znamená, že se extenze zbytečně natahuje a spouští na každém webu a může mít v některých případech negativní vliv na množství přenesených dat a výkon všech navtívených webů. Většina podporovaných e-shopů je plná měřících kódů a dalších, kde je stopa hlídače zanedbatelná.

PS Verze 1.8.1, učitě žádná nová oprávnění nepotřebovala.

**Comment by fczbkk** [comment]
Čisto teoreticky, toto by sa dalo vyriešiť pomocou optional permissions:
https://developer.chrome.com/extensions/permissions

Zoznam podporovaných shopov by mohol byť k dispozícii cez nejaké API. Rozšírenie by si mohlo na to API siahnuť a zistiť, či pribudla podpora pre nové shopy. To by sa mohlo prejaviť niekde v UI: "Chceš pridať podporu pre tieto shopy?" Ak užívateľ klikne na tlačítko, Chrome si vyžiada tie permissions a z pohľadu užívateľa je to kontextové a vedomé.

Pričom niekde v options stránke by mohlo byť tlačítko: "Chcem podporovať všetky shopy", čo by si vyžiadalo permission pre wildcard na úplne všetky URL a hotovo.

**Comment by rarous** [comment]
Chrome přichází s manifest v3, kde se bude k oprávněním přistupovat podobně jako v Safari, nebo jak píše Riki - pomocí Optional Permissions. V poslední době jsme žádné nové e-shopy nepřidávali. Když budeme přidávat nové e-shopy, budeme to dělat ve větších dávkách. Na aktuálním systému zatím nic měnit nebudeme, věci se změní s přechodem na Manifest v3.
