### ISSUE TITLE
Endpoint pro e-shopy

### ISSUE THREAD

**Issue by rarous** [topmonks/hlidac-shopu#13]
Pro potřeby website by bylo fajn mít enpoint, který vrátí seznam aktuálně podporovaných e-shopů s jejich statistikou.

Příklad API:

```
GET /e-shops

[
  {key: "alza", 
   name: "Alza.cz",
   url: "https://www.alza.cz",
   allProducts: 400000,
   bfProducts: 2000,
   avgClaimedDiscount: 0.43,
   avgRealDiscount: 0.21}
]
```

**Comment by padak** [comment]
hotovo!

- zavěsil jsem to za transformaci [shop_numbers](https://connection.eu-central-1.keboola.com/admin/projects/395/transformations/bucket/77611526/transformation/81197894)
- v storage je to [out.c-clean-data.shop_numbers_json](https://connection.eu-central-1.keboola.com/admin/projects/395/storage-explorer/out.c-clean-data/shop_numbers_json)
- do dynama to jde [tímhle](https://connection.eu-central-1.keboola.com/admin/projects/395/writers/kds-team.wr-dynamodb/82366790)
- scheduluje to [Dynamo](https://connection.eu-central-1.keboola.com/admin/projects/395/orchestrations/80689384) orchestrace
