### ISSUE TITLE
Zjednodušení rozšíření

### ISSUE THREAD

**Issue by rarous** [topmonks/hlidac-shopu#136]
Většina lidí neumí číst v grafech. Měli bychom jít na proti i lidem, kteří nemají analytický background, a pomoci jim data v grafu interpretovat. Pomalu jsme začali s vysvětlením slev. S přechodem na [novou metodiku](https://www.hlidacshopu.cz/metodika/) můžeme i říci o kolik bylo zboží zdraženo. Napadají mě následující věci, které dokážeme snadno najít a vysvětlit slevy:

Stejná cena -  Bez slevy
Podle nás zdraženo
Podle nás zlevněno
Na slevě se shodneme s prodejcem

A manipulace:

Za udávanou původní cenu se zboží neprodávalo/nemáme o tom informaci
Prodejce zvedl udávanou původní cenu před akcí
Prodejce zvedl prodejní cenu před akcí
Udávaná původní cena odpovídá našim datům

Osobně bych pak graf schoval, s možností ho otevřít. V nastavení by šlo zapnout, že se bude uživateli zobrazovat pořád.

**Comment by paulus-tom** [comment]
Navrhujem update vizuálu rozšírenia. Máme 3 verzie, ktoré sa líšia úplnými drobnosťami. Okrem pridania semaforu na zvýraznenie zľavy redizajnujeme aj jej zobrazovanie

Aká informácia je pre vás podstatnejšia?
- Celkové % zľavy?
- Pohyb pôvodnej ceny?

Aktuálne bojujeme s tým, že si užívateľ pri zdražení produktu (napr. o 20%) bude ignorovať (+) pred sumou. Tak vznikla druhá a tretia varianta.

Aké riešenie je pre vás zaujímavejšie?
- Použiť prvú variantu, ale v prípade zdraženia produktu použiť tretiu variantu
- Zachovať konzistenciu a používať iba prvú variantu

Ja sa prikláňam ku konzistencii. A čo vy?:) 

Po kliknutí na "Zobrazit vývoj ceny" zobrazíme graf :)

![image](https://user-images.githubusercontent.com/39488664/99879552-0d587f80-2c0e-11eb-85d3-605b74bc8faf.png)

**Comment by jakluk** [comment]
Určitě nechat možnost zobrazit graf která nebude utopená, já si hodnoty na grafu umím představit líp než samotné číslo. Navíc je otázkou co je cílem tohoto projektu, jestli jen upozorňovat na zavádějící slevové akce, nebo být rádcem co se děje s produktem (např. jestli už byl zlevněn loňský model mobilu po vydání nové generace). Ten nový model s druhým případem vůbec nepočítá.

Není mi jasné co znamenají ty barvy a ikony, můj tip (nevím jestli správný):
* Zelená: Produkt ve slevě stejné nebo vyšší než udávané
* Žlutá: Produkt ve slevě která je nižší než udávaná
* Červená: Produkt je zdražen, nebo je uvedena sleva ale cena se nezměnila, nebo se sleva výrazně liší
* Produkt má konstantní cenu a není uvedena sleva

Zelenému bych dal ikonu ✔️ a žlutému ⚠️. Ideálně také slovní popis co je důvodem udělené barvy, třeba po najetí na otazník.

**Comment by keivulan** [comment]
Zdravím pánové.

Pokud by Vám nevadil názor uživatele rád bych přispěl k tématu. 
Projekt sleduji od začátku a byl jsem velice překvapený, jak to funguje. Prodejci Vás měli v hledáčku během velice krátké doby a tak mi bylo jasné, že už s vámi musejí počítat a o hodně se zlepšili.

Nevím, kde se vzala informace, že lidi neumí číst s grafu? Osobně jsem to doporučil a nainstaloval minimálně patnácti lidem starším 60 let. Hlavně když se rozjelo to Tesco. 
Nyní zhruba týden zpět je graf rozbitý a nefunguje jak má. Graf je od začátku dobře vymyšlený a pak se postupně přidali vylepšení je zcela transparentní od prvního dne, kdy se produkt objeví. Uživatel muže pokud chce po celou dobu sledovat, jak se cena vyvíjela.
Já bych ocenil, kdyby se vrátil funkční graf a přidalo se tam tlačítko na změnu vzhledu.  Jedním klikem získám nové rozhraní jen s informacemi:
Stejná cena - Bez slevy
Podle nás zdraženo
Podle nás zlevněno
Na slevě se shodneme s prodejcem
Grafické znázornění je určitě nejlepší způsob jak prezentovat zda se produkt opravdu zlevnil nebo ne, ale určitě bych nebral graf.
Jinak to znázornění od paulus-tom není vůbec špatné.  To zjednodušené zobrazení dá velice rychle informaci, zda sleva je reálná nebo není. A hlavně stále by tam byla možnost vyvolat graf.
Viz. „Po kliknutí na "Zobrazit vývoj ceny" zobrazíme graf :)“
Na závěr bych se chtěl zeptat, proč tam uvádíte „Sleva dle nás“?

**Comment by rarous** [comment]
@keivulan můžu vás poprosit o popis "Nyní zhruba týden zpět je graf rozbitý a nefunguje jak má" do nové issue?

**Comment by jakubbalada** [comment]
@jakluk cilem projektu od zacatku bylo a stale je upozornovat na zavadejici slevy. Aktualnim praktickym cilem je motivovat e-shopy a nasledne je kontrolovat v dodrzovani nove EU smernice, ktera ma do konce roku 2020 vstoupit v platnost. 

@keivulan „Sleva dle nás“ je nami vypocitana realna sleva. Chteli bychom uz zobrazovat slevu podle EU smernice, ale je zatim vagni, cekame na implementaci do ceskeho zakona.

@rarous k tomu grafu - jeste bych hlasoval pro zobrazeni grafu jako default s moznosti prejit na strucnejsi verzi zobrazeni v nastaveni. Tim padem by graf meli defaultne i stavajici uzivatele.

**Comment by rarous** [comment]
Pro mne je primární motivací pro malý Widget možnost ho posunout blíže k ceně/slevě a neodsouvat tím moc tlačítko Přidat do košíku. Na což si eshopy stěžovaly a chápu proč. Variantou je i rozdělit Widget na více kusů. Graf zachovat tam, kde je, a semafor se slevou a běžnou cenou posunout nahoru v nějakém minimal tvaru.

**Comment by jakubbalada** [comment]
Ja si jen nejsem jistej, ze pro uzivatele Hlidace plati "Většina lidí neumí číst v grafech". I z feedbacku tady je videt, ze graf je stezejni. Plus bych byl pro, aby jakykoliv nas widget byl pod tlacitkem pridani do kosiku.

**Comment by rarous** [comment]
Co jsem já měl možnost sledovat nemalé množství uživatelů, tak v tom četli něco jinýho, než ten graf říká. Věřím, že badge se slevou pomáhá lépe chápat zobrazená data, ale občas mate i lidi, co si myslí, že těm datům rozumí. 

Dále je také otázka, zda chceme uspokojovat 20k lidí, co si myslí, že umí číst graf, nebo pomoci i těm dalším statisícům, co si to nemyslí? :) 

Neberte to, prosím, tak, že chci šlapat po argumentaci ostatních, spíše chci prohloubit diskusi a neberu nic jako jasně daný. Čím více různých pohledů, tím více dat pro to se někam posunout.

**Comment by jakubbalada** [comment]
Jasny, chapu. Myslim, ze se vshichni shodnem na novy lightweight variante bez grafu. Dulezity je, aby byla moznost zobrazit i graf a aby i novy uzivatel jasne pochopil, ze tam ta moznost je a kde ho muze rozbalit. Plus v nastaveni moznost prepnout default variantu. Ze nebude vychozi varianta s grafem asi zkousnu :-)

**Comment by paulus-tom** [comment]
Drobný update: ![image](https://user-images.githubusercontent.com/39488664/100797671-cd21aa00-3422-11eb-91b1-b095e408a34e.png)

Premýšľam ešte nad jednou zmenou. Čo pre vás znamená "Poslední cena před akcí?". Napadá mi ešte jeden enhancement. Je ale možné, že hasím oheň, ktorý nikoho nepáli :D 

![image](https://user-images.githubusercontent.com/39488664/100797747-e9bde200-3422-11eb-967c-a4a2a24cb15d.png)
