### ISSUE TITLE
Top slevy - online a rozšíření

### ISSUE THREAD

**Issue by radekvaclavik** [topmonks/hlidac-shopu#138]
Seznam top slev je užitečná funkce. Nicméně je zobrazována se zpožděním (cca 1 den - často se stává, že po rozkliknutí konkrétního produktu už udávaná cena neplatí). Bylo by hezké, kdyby tento seznam vycházel z aktuálních dat.

Uvítal bych také rozšíření počtu produktů v seznamu - ne pouze TOP 100, ale prakticky neomezeně.

A do třetice mi přijde, že zasílání top slev na email nefunguje - alespoň mně žádné emaily nechodí.

Díky.

**Comment by rarous** [comment]
@radekvaclavik Dobrý den. Top Slevy jsou experimentální feature, kterou připravili naši kolegové. Zpětnou vazbu jsem jim předal.
