### ISSUE TITLE
Nefunkční graf

### ISSUE THREAD

**Issue by keivulan** [topmonks/hlidac-shopu#139]
Před nějakým updatem měl graf vodící kolečka kde ukazoval v bublině informace.
Nyní je nemá a graf se tváří jako nefunkční.

https://youtu.be/TbrRFbx4iHI

**Comment by rarous** [comment]
Máte pravdu, chová se to podivně. Připravil jsem úpravu, která by měla chování zlepšit. Čeká na schválení.

**Comment by rarous** [comment]
Příčina jiného chování, je v tom, že jsme začali používat novou verzi knihovny pro vykreslení grafu a zároveň jsme začali používat shadowDOM, který by měl extenzi ve stránce více zapouzdřit od okolí. V tomto režimu se ale špatně počítají pozice, kam se má tooltip vykreslit. Chyba už byla v knihovně opravena https://github.com/chartjs/Chart.js/commit/fa997f06e23e2644ce1985de51b9dfbf2e7426df, mezitím jsem shadowDOM vypnul.

**Comment by rarous** [comment]
@keivulan vyzkoušejte prosím poslední aktualizaci (verze 1.8.7)

**Comment by keivulan** [comment]
Nyní je to v pořádku a funguje to parádně.

**Comment by rarous** [comment]
Super, díky za spolupráci a omlouvám se za problémy. Hezký Black Friday týden.
