### ISSUE TITLE
Novy graf (extension v 1.0.0) zobrazuje necitelnout x-ovou osu

### ISSUE THREAD

**Issue by jakubbalada** [topmonks/hlidac-shopu#14]
Priklad:
https://www.alza.cz/homedics-gel-shiatsu-sgm-1600h-d5450167.htm
<img width="456" alt="Screen Shot 2019-11-04 at 00 01 52" src="https://user-images.githubusercontent.com/14894832/68093508-77cd3f00-fe96-11e9-82a1-2451ca747df4.png">

**Comment by rarous** [comment]
Sladil jsem graf s tím, jak je to na webu, už by tam měl být krok po 14 dnech, možná ho brzy posunem na 30 dní :)

**Comment by theodik** [comment]
ale u některejch shopů je tam nascrapováno jen pár dní, tam pak nebyli datumy vůbec

**Comment by theodik** [comment]
proto sem dával stepUnit pryč

**Comment by rarous** [comment]
V tom případě, to budem muset udělat dynamicky podle množství dat

**Comment by rarous** [comment]
Vyřešili jsme to tím, že se vždy vygeneruje cca 14 ticků na ose, tím že dynamicky měníme step na základě dat.
