### ISSUE TITLE
Alza.cz - chyba ceny kvůli novému sdílení produktů

### ISSUE THREAD

**Issue by Hammanek** [topmonks/hlidac-shopu#151]
Ahoj,

Alza zavedla vymoženost ve smyslu sdílej produkt, nakup s více lidmi najednou a měj nižší cenu, díky tomu je chyba v grafu, protože je zaznamenávána právě ta cena po sdílení a ne klasická

Příklad zde:

https://www.alza.cz/candy-mic-20-gdfx-d5478765.htm

Na produkt koukám už pár dní, cena je stále 3190,- , ale graf si myslí, že historicky byla 2649,-. Je špatně vždycky odedne dozadu, aktuální den je v grafu správně.

**Comment by rarous** [comment]
Dokážeme v kódu stránky nějak rozlišit, že je přihlášený firemní zákazník? Pokud ano, můžeme na takové stránce neparsovat poslední data point.

**Comment by Hammanek** [comment]
Během toho roku tu svoji sdílecí akci zrušili, tak už je tento problém nerelevantní, pokud ji tedy zase nezavedou..
