### ISSUE TITLE
Problem s instalaci Safari extension

### ISSUE THREAD

**Issue by jakubbalada** [topmonks/hlidac-shopu#165]
Z mailu Hlidace:

_Dobrý den, 

narazil jsem na nekorektní funkcionalitu Vašeho doplňku v int. prohlížeči Safari, kde po instalaci doplňku se zobrazí okno „Dokončit nastavení“, které „neprovádí“ žádnou akci a v prohlížeči/Rozšíření nedojde k přidání. 

Verze 13.1.1 (15609.2.9.1.2) - Safari 
Verze 10.15.5 (19F101) - MacOS 

Děkuji za zpětnou vazbu a přeji hezký den._

**Comment by rarous** [comment]
@jakubbalada Ať si aktualizuje Safari na 14. Používáme jeho podporu pro Web Extension, kteoru 13 a předchozí neměli.
