### ISSUE TITLE
404 on Alza Macbook

### ISSUE THREAD

**Issue by Strajk** [topmonks/hlidac-shopu#167]
https://www.alza.cz/macbook-air-13-m1-cz-vesmirne-sedy-2020-d6252312.htm
https://api2.hlidacshopu.cz/detail?itemId=6252312&title=Macbook+Air+13%22+M1+CZ+Vesm%C3%ADrn%C4%9B+%C5%A1ed%C3%BD+2020&currentPrice=58044&originalPrice=59990&imageUrl=https%3A%2F%2Fcdn.alza.cz%2FFoto%2Ff3%2FNL%2FNL244a1j.jpg&url=https%3A%2F%2Fwww.alza.cz%2Fmacbook-air-13-m1-cz-vesmirne-sedy-2020-d6252312.htm&ext=1.8.10

**Comment by rarous** [comment]
@Strajk není to v datech, tj. tohle je na Václava nebo na Zuzku.

**Comment by Strajk** [comment]
@rarous sry for lazy bug report, Jakub Balada made me do it :D
