### ISSUE TITLE
tsbohemia umisteni grafu

### ISSUE THREAD

**Issue by zpelechova** [topmonks/hlidac-shopu#17]
je blbe na strance - uzke, protoze vedle toho je splatkova kalkulacka. Nejde mi sem dat screenshot, tak aspon link: https://www.tsbohemia.cz/samsung-gear-vr-2019_d329100.html

**Comment by theodik** [comment]
jj o tom vim, pak se na to mrknu, měnili layout

**Comment by rarous** [comment]
Fixed in v1.1.0
