### ISSUE TITLE
notino nezobrazuje original price - jeste musim ceknout, ale odkladm si sem

### ISSUE THREAD

**Issue by zpelechova** [topmonks/hlidac-shopu#18]

**Comment by VaclavRut** [comment]
@zpelechova ja je tam vidim https://www.notino.cz/hugo-boss/boss-the-scent-toaletni-voda-pro-muze/ ale nevim jestli je to po fixu

**Comment by zpelechova** [comment]
@VaclavRut Jj, to jsem psala v jinem issue, theodik to resi, jak to neni full load, tak je to jine nez u ostatnich shopu

**Comment by rarous** [comment]
Problém je v tom, že Notino může URL dle jejich slov "přemástrovat". Na stejné URL můžou v čase měnit jaká varianta produktu se tam zobrazuje, tj. mění se dynamicky cena a nejde určit, že jde o jinou variantu. Úplně by stačilo, aby jim ta master adresa dělala redirect na URL konkrétní varianty produktu (další segment za lomítkem) a vše by fungovalo, jak má.
