### ISSUE TITLE
kompatibilita se staršími browsery

### ISSUE THREAD

**Issue by vpil** [topmonks/hlidac-shopu#197]
Používám Waterfox Classic (založený na jádře asi z Firefoxu 57 nebo tak nějak) a všiml jsem si, že doplněk hlidacshopu 1.8.1 přestal cokoli zobrazovat. Hm, vidím, že od verze 1.8.2 poskočily na minimální Firefox 78 (+30). V aktuálním FF to funguje.

Problém je, že nyní nefunguje ani web hlidacshopu.cz (nezobrazí se seznam podporovaných shopů, nefunguje kontrola produktu) namátkou v těchto browserech:
Waterfox Classic 2020.12
Edge 44 (s EdgeHTML)
MSIE 11

Jde o chyby ve skriptech, např:
SyntaxError: expected expression, got keyword 'import' index-c443a5162c.js:2:5945

Pokud už tedy nutně potřebujete začít používat featury dostupné jen v nejnovějších HTML/JS enginech (škoda), tak nebylo by korektní nekompatibilitu detekovat a zobrazit na webu a v doplňku upozornění místo nefunkčnosti? Děkuji.

**Comment by rarous** [comment]
Uvěřování na webu určitě nikdy nepodporovalo nemoderní prohlížeče. Vždy jsme plně běželi ve `<script type module>`. Extenze sice fungovala, ale pro nás není udžitelné podporovat několik odlišných codebases. Ve verzi 1.8 došlo ke sjednocení extenze a webu na úrovni velké části kódu, aby se nám zjednodušila údržba a rozvoj.

Omlouváme se, že zrovna vám Hlídač nefunguje, ale Hlídač shopů je zdrama a je neziskovým projektem.

**Comment by rarous** [comment]
Kompatibilita s firefox57 a safari12 by měla být nna webu nastavená jako kompilační baseline. U extenze zkusím udělat to samé v dalším releasu. Kompatibilitu s IE a Edge řešit nejspíše nebudeme.
