### ISSUE TITLE
Spatna (puvodni) description v nahledech

### ISSUE THREAD

**Issue by jakubbalada** [topmonks/hlidac-shopu#20]
![D4188088-8EA4-4314-BF21-782552053A15](https://user-images.githubusercontent.com/14894832/68241733-812de700-000f-11ea-9e86-522a4679da62.jpeg)

**Comment by rarous** [comment]
@jakubbalada jaká má být?

**Comment by jakubbalada** [comment]
Dal bych tam tu, co je na webu: "Ujistěte se, že nakupujete opravdu se slevou"
