### ISSUE TITLE
Chybna preskrtnuta cena pro aktualni den v grafu na webu Hlidace

### ISSUE THREAD

**Issue by jakubbalada** [topmonks/hlidac-shopu#206]
V extension spravne: https://www.mall.cz/televizory/lg-75nano99
Na webu spatne (puvodni cena 0): https://www.hlidacshopu.cz/?url=https%3A%2F%2Fwww.mall.cz%2Ftelevizory%2Flg-75nano99

<img width="592" alt="Screen Shot 2020-12-14 at 15 17 19" src="https://user-images.githubusercontent.com/14894832/102091930-bebe8f80-3e1f-11eb-9e76-8abce7dcd222.png">
<img width="545" alt="Screen Shot 2020-12-14 at 15 17 00" src="https://user-images.githubusercontent.com/14894832/102091945-c2521680-3e1f-11eb-90f8-fabc0cabd8f1.png">

**Comment by rarous** [comment]
Opraveno v e7d1a6710c051877d7381b329002fa401627b754
