### ISSUE TITLE
iOS UI drobnosti

### ISSUE THREAD

**Issue by jakubbalada** [topmonks/hlidac-shopu#219]
Z inboxu Hlidace:

Dobry den,
posilam maly feedback k iOS aplikaci - vsiml jsem si dvou veci, viz screenshoty:

* [ ] bila oblast s napovedou dole nezasahuje pod home indikator, vypada to neprirozene
* [x] kdyz textove pole dostane fokus, zobrazi se border, ktery rozbije iluzi jednoliteho pole s ikonou
![IMG_3446](https://user-images.githubusercontent.com/14894832/102695184-04b39300-4226-11eb-9edd-eba034761523.png)
![IMG_3447](https://user-images.githubusercontent.com/14894832/102695189-08471a00-4226-11eb-898b-7083050a7e49.png)

**Comment by ondrejhanak** [comment]
Dobry den, mail je ode me.

Prvni bod se da lehce vyresit prepinovanim webview, muzu poslat PR.
Druhy je potreba vyresit ve webove casti.

**Comment by rarous** [comment]
Druhá část je už fixnutá, vč validace.

@ondrejhanak PR určitě vítána. Ale pozor, že na detailu výsledku je spodek fialový a tam by to také vypadalo nepřirozeně, jen obráceně. My ještě chystáme nějaké úpravy UI a nedokážu teď ještě říct, jak bude výsledek vypadat.
