### ISSUE TITLE
Počítání slevy v % na webu

### ISSUE THREAD

**Issue by VaclavRut** [topmonks/hlidac-shopu#22]
![Screenshot 2019-11-06 at 10 57 19](https://user-images.githubusercontent.com/7426343/68288277-677ab700-0084-11ea-8447-b3d23ab63a36.png)
`https://www.hlidacshopu.cz/?url=https%3A%2F%2Fwww.czc.cz%2Fxiaomi-mi-band-4-cerna%2F263000a%2Fprodukt`

Správně je 31%

**Comment by rarous** [comment]
"Správně" je dost subjektivní pojem. Připravujeme výpočet slevy podle jednotné metodiky napříč celým Hlídačem.
