### ISSUE TITLE
CZC.CZ - Povánoční výprodej neukazuje graf

### ISSUE THREAD

**Issue by akaspeh1** [topmonks/hlidac-shopu#248]
V povánočních výprodejích na czc.cz se nezobrazuje graf, protože nejspíše k těmto produktům chybí data.
Přitom když url zkopíruji přímo do https://www.hlidacshopu.cz/ tak to produkt nalezne a ukáže graf v pořádku.

Příklad produktů: 
https://www.czc.cz/epico-power-bank-eloop-by-epico-e12-cerna/182442a/produkt
https://www.czc.cz/samsung-galaxy-a41-4gb-64gb-blue/285153a/produkt

Vystup z requestu z addonu na backend:
`{error: "Missing data", itemId: "182442a"}
error: "Missing data"
itemId: "182442a"
`
Výpis z konzole:
![image](https://user-images.githubusercontent.com/1347327/103442367-c53d6b80-4c55-11eb-9d6d-625de950f601.png)

**Comment by rarous** [comment]
Oraveno ve verzi 1.8.13
