### ISSUE TITLE
slovenské eshopy

### ISSUE THREAD

**Issue by jooray** [topmonks/hlidac-shopu#25]
Ak by sa vám chcelo pridať podporu pre eurá a slovenské eshopy, aspoň tie, ktoré sú aj na SK aj CZ, teda majú podobný web, mnohých z nás by to potešilo.

Na oplátku spropagujeme toto rozšírenie aj na Slovensku vrámci Paralelnej Polis.

**Comment by jakubbalada** [comment]
Premyslime o tom, minimalne Alzu na Slovensku uz scrapujeme. Pripadne nam muzete pomoct nastavit scrapery na Apify na dalsi slovenske eshopy (a pull request na extension)

**Comment by jooray** [comment]
Ja pravdupovediac používam iba alzu zo slovenských eshopov, inak používam amazon.

**Comment by animator013** [comment]
+1 za alza.sk
