### ISSUE TITLE
Alza.cz - Safari - generuje se dvakrát

### ISSUE THREAD

**Issue by spenat28** [topmonks/hlidac-shopu#258]
Systém Big Sur (poslední MacOS)
Poslední verze Safari

Aplet se generuje dvakrát. (U všech produktů.)
Příklad:
<img width="1259" alt="Screenshot 2021-01-05 at 1 02 04 PM" src="https://user-images.githubusercontent.com/1527247/103644218-4a769800-4f56-11eb-9cd5-dee8399c34e2.png">

**Comment by rarous** [comment]
@spenat28 Dobrý den, díky za report. Můžu vás poprosit, jestli byste se podíval pomocí web inspectoru, jakou verzi ty aplety mají? A jestli je u obou stejná? Najdete ji v obalovém divu v atributu `data-hs`. Extenze by měla vždy vkládat jen jednu instaci. Já ve svém Big Sur Safari s poslední verzí extenze vidím jen jednu instanci. Děkuji

**Comment by spenat28** [comment]
@rarous Ano, maji oba: 1.8.13
Omlouvam se za opozdenou odpoved. Problem stale trva.

System aktualizovan, Safari take, a zacalo se to dit po updatu pluginu. Nebo prechodu na BigSur. To uz si jisty nejsem.
Pokud me nejak navedete, mohu vam s debuggingem pomoc, nebo mi poslete mail a muzem si kvuli tomu zavolat treba po HO nebo tak - to neni problem.

Zadne doplnky co mam na to nemaji vliv, vyplnul jsem vsechny - beze zmeny.
