### ISSUE TITLE
Alza.cz - chybi graf ceny

### ISSUE THREAD

**Issue by michalzemko** [topmonks/hlidac-shopu#266]
Uplne zmizel graf ceny z hlidacshopu na alza.cz. Viz screenshot
![image](https://user-images.githubusercontent.com/4049243/104005103-ea296580-51a4-11eb-8e10-9b8f0d07fa54.png)

**Comment by rarous** [comment]
@michalzemko Dobrý den, ano to je správně, používáte starou verzi extenze. Aktualizujte si ji, prosím, a vše vám bude fungovat.

**Comment by michalzemko** [comment]
@rarous Dobry den, reinstal rozsireni jsem zkousel, ted jsem znovu jsem odinstaloval rozsireni a opet nainstaloval pres odkaz z https://www.hlidacshopu.cz/ a graf stale nikde. Nainstalovanou mam stejnou verzi co je v chrome store 
![image](https://user-images.githubusercontent.com/4049243/104006438-c9620f80-51a6-11eb-9756-1a8d68fb2b48.png)

**Comment by rarous** [comment]
Pak máte Hlídač nainstalovaný dvakrát. V liště máte ikonu Hlídače z listopadu 2019.

**Comment by michalzemko** [comment]
@rarous  Po kliknuti na ikonu z 2019 pise spravnou verzi 1.8.13:
![image](https://user-images.githubusercontent.com/4049243/104006796-49887500-51a7-11eb-8a3e-e9e6e9867694.png)
A v extensions nemam stejnou extension 2x:
![image](https://user-images.githubusercontent.com/4049243/104006870-645ae980-51a7-11eb-995a-c98d287f47fe.png)
Mezi reinstal-instal jsem samozrejme restartnul browser. Mate nejaky navod jak uplne odstranit extension nez klasicky pres "Remove" button?

**Comment by rarous** [comment]
Tak ikona je aktuální, ale pro monitory s nízkým rozlišením. Zkuste si zapnout Developer Mode a podívat se, co to píše v logu. Případně jestli vám ji neblokuje Adblock. 
![image](https://user-images.githubusercontent.com/101581/104008057-2ced3c80-51a9-11eb-88b1-6b66de8d6be4.png)

**Comment by michalzemko** [comment]
Nechal jsem zapnutou jen extension hlidacshoupu, restartnul browser, a stejny vysledek. V konzole nevidim nic 
![image](https://user-images.githubusercontent.com/4049243/104008729-1c899180-51aa-11eb-9fa0-92c408f71ef6.png)

Nejaky navod kam se kouknout do logu?

**Comment by rarous** [comment]
Zkuste ještě Details a tam se ujistit, že máme povolený přístup:
![image](https://user-images.githubusercontent.com/101581/104009267-10520400-51ab-11eb-948b-4ec78a5d0f20.png)

**Comment by michalzemko** [comment]
Ano, povoleno je vse, viz 2. screenshot .

**Comment by rarous** [comment]
Koukám do těch vašich logů a vůbec se nechytne extenze na žádný ze známých elementů, takže neproběhne scrape dat. Můžu vás poprosit o zkopírování kódu stránky v záložce Elements v DevTools?

**Comment by michalzemko** [comment]
Pri zkouseni v inkognito mode se extension rozbehla, pak po promazani cookies jede i normalne. V extension setting nicmene vypisuje errors 
![image](https://user-images.githubusercontent.com/4049243/104019731-60859200-51bc-11eb-826f-54b778b1c7a3.png)

Dalsi problem je, ze graf s cenou po najeti mysi ukaze popup s cenou k datu, ale po sekunde zmizi a popup sa uz neobjevi - stejne se chova alza, mall, datart ...
