### ISSUE TITLE
Alza - chybne vypocitana sleva pro firemni zakazniky

### ISSUE THREAD

**Issue by jakubbalada** [topmonks/hlidac-shopu#267]
Na obrazku vpravo je standardni zobrazeni pro bezneho uzivatele.
Na obrazku vlevo je zobrazeni pro firemniho zakaznika, ktery ma aktualni cenu malinko mensi.

Sleva by mela byt lehce jina, ale ne takto rozhozena.

I po vyreseni tohoto bugu to nebude idealni, mozna by bylo lepsi pro firemni zakazniky se slevou nebrat aktualni cenu, ale zobrazovat cenu z DB pro bezneho uzivatele (jeste lepe s nejakou poznamkou).

URL produktu: https://www.alza.cz/samsung-970-evo-1tb-d5319058.htm

![137501551_485820342414267_1482609680273183947_n](https://user-images.githubusercontent.com/14894832/104092398-f59f8e00-5283-11eb-8806-704bd0286b3a.png)

**Comment by rarous** [comment]
Dokážeme v kódu stránky nějak rozlišit, že je přihlášený firemní zákazník? Pokud ano, můžeme na takové stránce neparsovat poslední data point.

**Comment by rarous** [comment]
Nemáme dostatečné podklady pro vyřešení

**Comment by lenoch0d** [comment]
> Dokážeme v kódu stránky nějak rozlišit, že je přihlášený firemní zákazník? Pokud ano, můžeme na takové stránce neparsovat poslední data point.

Vypadá to, že firemní zákazník má pod vyhledávacím polem přidaný banner s textem ,,Právě nakupujete za zvýhodněné ceny."  nebo v případě EN ,,Wholesale prices active".


![image](https://user-images.githubusercontent.com/17928766/179008931-ba75f7b1-41ee-49f3-ba39-f87bd422043c.png)
