### ISSUE TITLE
Spatne vykresleni barev v grafu

### ISSUE THREAD

**Issue by jakubbalada** [topmonks/hlidac-shopu#27]
Kdyz zbozi neni zlevneno, tak v grafu ma byt pouze cervena, nikoliv modra cena.
Viz napr. https://www.alza.cz/sport/goodjump-4upvc-modra-trampolina-305-cm-s-ochrannou-siti-zebrik-d5114026.htm
<img width="775" alt="Screen Shot 2019-11-10 at 21 23 40" src="https://user-images.githubusercontent.com/14894832/68550148-95ebef80-0400-11ea-8f9c-37b32a2f4588.png">

**Comment by jakubbalada** [comment]
Tady je to rozbity jeste vic:
https://www.kosik.cz/produkt/le-co-kureci-sunka-pro-deti-nejvyssi-jakost-platky
Je to asi dany navazovanim rady, kdyz chybi data

<img width="445" alt="Screen Shot 2019-11-10 at 21 38 17" src="https://user-images.githubusercontent.com/14894832/68550360-66d67d80-0402-11ea-98ec-60b30befc003.png">

**Comment by zpelechova** [comment]
https://apifier.slack.com/archives/CEB8J8UCT/p1573466155008200

**Comment by rarous** [comment]
Opraveno v nové verzi extenze
