### ISSUE TITLE
Nektere produkty Datartu nefunguji na webu

### ISSUE THREAD

**Issue by jakubbalada** [topmonks/hlidac-shopu#30]
https://www.datart.cz/televize-jvc-lt-65vu3905-cerna.html funguje v rozsireni, ale nefunguje na webu

**Comment by rarous** [comment]
Já na https://www.hlidacshopu.cz/?url=https%3A%2F%2Fwww.datart.cz%2Ftelevize-jvc-lt-65vu3905-cerna.html vidím výsledek. Můžná byla studená lambda a nestihl přijít výsledek do 4s, pak to v UI timeoutuje...
