### ISSUE TITLE
Na iPhone SE (Chrome) se nedari vlozit odkaz na detail produktu

### ISSUE THREAD

**Issue by jakubbalada** [topmonks/hlidac-shopu#33]
Focus do inputu se nechce chytnout, viz
https://twitter.com/i/status/1199037515866476545

**Comment by rarous** [comment]
Problém je ve vrstvě schovaného menu hodně mmalého displaye. Chystáme se horní menu předělat, budeme počítat s touto issue. Zatím je workaround https://www.hlidacshopu.cz/app/.

**Comment by rarous** [comment]
Opraveno.
