### ISSUE TITLE
Appka pro iOS

### ISSUE THREAD

**Issue by rarous** [topmonks/hlidac-shopu#34]
iOS bohužel neumí Web Share Target API a tak nelze PWA použít jako na Androidu. Bylo by fajn mít iOS appku, která:
* [x] Implementuje [share extension](https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/Share.html) na úrovni systému
* [x] Embedduje [PWA](https://www.hlidacshopu.cz/app/) do WebView a bude jí předávat informace ze share (GET parametr `url`).

**Comment by rarous** [comment]
Budeš mít na to @junkycoder čas a chuť?

**Comment by junkycoder** [comment]
Ready to go. Snad brzy ve vašich App Stórech.

**Comment by junkycoder** [comment]
Cekame na publikaci, ale budis uzavreno :)

po 9. 12. 2019 v 16:00 odesílatel Aleš Roubíček <notifications@github.com>
napsal:
