### ISSUE TITLE
Script pro automaticke verze

### ISSUE THREAD

**Issue by junkycoder** [topmonks/hlidac-shopu#36]
Priprava nove verze ted obnasi 

1. rucni prepsani verze v manifest.json
2. rucni prepsani verze v about.html
3. commitnout zmenu verze
4. spusteni `npm run bundle:osx` (coz udela dalsi commit)

Idealni by byl script npm run version 1.3.3, ktery by toto udelal automaticky.

**Comment by rarous** [comment]
ideálně by se verze brala z `package.json`

**Comment by junkycoder** [comment]
Ano

čt 28. 11. 2019 v 6:02 odesílatel Aleš Roubíček <notifications@github.com>
napsal:
