### ISSUE TITLE
Datart - vyprodane zbozi - nezobrazuje se graf i kdyz mame data

### ISSUE THREAD

**Issue by zpelechova** [topmonks/hlidac-shopu#37]
https://www.datart.cz/bezdratova-sluchatka-sony-wh-xb900n-extra-bass-s-technologii-pro-odstraneni-sumu-545149.html

**Comment by rarous** [comment]
Já ho vidím naskladněný a s grafem :-/

**Comment by rarous** [comment]
Duplikace #10
