### ISSUE TITLE
Chybny vypocet realne slevy

### ISSUE THREAD

**Issue by jakubbalada** [topmonks/hlidac-shopu#40]
Treba zde: https://www.alza.cz/iphone-xr?dq=5460703
<img width="587" alt="Screen Shot 2019-12-01 at 17 14 28" src="https://user-images.githubusercontent.com/14894832/69916668-103aed00-145e-11ea-8815-fcea5cb2c892.png">

**Comment by rarous** [comment]
Problém je v neaktuálnosti metadat:
```
{
  "pkey": "alza:iphone-xr",
  "shop": "alza",
  "real_sale": "0.00",
  "itemImage": "https://cdn.alza.cz/Foto/f1/RI/RI027b4.jpg",
  "itemUrl": "iphone-xr",
  "itemId": "xr?q=5460705",
  "max_price": "15990.00",
  "itemName": "iPhone Xr 64GB modrá"
}
```

**Comment by jakubbalada** [comment]
Dalsi priklad: https://www.alza.cz/macbook-pro-15-retina-2018-s-touch-barem?dq=5719463&o=3
<img width="591" alt="Screen Shot 2019-12-02 at 22 52 04" src="https://user-images.githubusercontent.com/14894832/69998358-70ad5580-1556-11ea-979a-9058739e8898.png">

**Comment by theodik** [comment]
problém s metadaty zde #58
