### ISSUE TITLE
iOS nedostatky

### ISSUE THREAD

**Issue by junkycoder** [topmonks/hlidac-shopu#42]
- [x] cerny appheader i kdyz pwa ma bile pozadi (bg bylo ez, ale neslo mi nastavit cernej text)
- [x] splashcreen podle navrhu (zatim jen vycentrovane logo)
- [x] activity indikator pred nactenim pwa do webView (ted flashuje prazdna obrazovka)
- [ ] dark mode support (pwa prepinat do dark sobrazeni?)
- [x] sdilet do aplikace z ofiko appek eshopu (nyni podporuje pouze sdileni ze safari)
  - [x] https://apps.apple.com/cz/app/alza/id582287621
  - [x] https://apps.apple.com/cz/app/czc-cz/id1020875138
  - [x] ...

**Comment by rarous** [comment]
@junkycoder appheader je v PWA už fixnutý; darkmode by asi měl fungovat až bude v PWA naimplementový OOTB

**Comment by rarous** [comment]
Občas je potřeba, sdílení otevřít dvakrát, aby se zobrazil Hlídač Shopů v nabídce cílů.

**Comment by rarous** [comment]
m.alza.cz má (nahlášený) bug v aktualizaci metadata, pokud se navigujete mezi více stránka, sdílí vždy první v navigačním řetězu. Doporučujeme používat nativní appku Alzy, kde sdílení funguje správně, nebo před ověřením udělat refresh stránky.

**Comment by rarous** [comment]
problém se sdílením je bug v iOS https://developer.apple.com/forums/thread/662671
