### ISSUE TITLE
Report 1

### ISSUE THREAD

**Issue by keivulan** [topmonks/hlidac-shopu#43]
https://www.alza.cz/beauty/calvin-klein-beauty-edp?dq=193078	Reálná sleva* NaN % 26 března byla puvodní 2490Kč Update 16 listopadu 699Kč

https://www.alza.cz/niceboy-hive-2-joy-d5704529.htm Reálná sleva* -33 %

https://www.alza.cz/sandisk-ultra-dual-64gb-type-c-d4423223.htm Reálná sleva* -20 %

**Comment by zpelechova** [comment]
Opraveno.
