### ISSUE TITLE
Spatna puvodni cena (a sleva) na webu Hlidace

### ISSUE THREAD

**Issue by jakubbalada** [topmonks/hlidac-shopu#46]
Napr. https://www.rohlik.cz/?productPopup=1294559-okurka-hadovka-cca-300g&cartUpdateSource=%3ASearch%3AProduct%3Adefault 
Zadna puvodn icena na webu aktualne neni, extension funguje spravne, ale na webu Hlidace zobrazujem spatnou puvodni cenu a tim i slevu
<img width="542" alt="Screen Shot 2020-01-30 at 19 48 51" src="https://user-images.githubusercontent.com/14894832/73480426-23086a00-439a-11ea-825e-fbecb55e2a57.png">
<img width="829" alt="Screen Shot 2020-01-30 at 19 54 42" src="https://user-images.githubusercontent.com/14894832/73480558-6236bb00-439a-11ea-8f00-e67425c6fa77.png">

**Comment by zpelechova** [comment]
Opraveno.
