### ISSUE TITLE
Graf na webu neobsahuje aktualni data

### ISSUE THREAD

**Issue by jakubbalada** [topmonks/hlidac-shopu#48]
Priklad (v extension je to cajk):
https://www.mironet.cz/xiaomi-mi-9-lite-6128gb-modra-639quot-oc-2x226x17ghz-6gb-ram-128gb-4882mp32mp-ds-android-9+dp413115

**Comment by theodik** [comment]
teď vidim graf stejnej jak na webu a ext 🤷‍♂
