### ISSUE TITLE
reálná sleva -1% v ext 0% na webu - "real_sale: 0.34"

### ISSUE THREAD

**Issue by theodik** [topmonks/hlidac-shopu#51]
https://www.mironet.cz/xiaomi-mi-9-lite-6128gb-modra-639quot-oc-2x226x17ghz-6gb-ram-128gb-4882mp32mp-ds-android-9+dp413115/

Kde je chyba? 😂

**Comment by zpelechova** [comment]
Jiné zaokrouhlování?

**Comment by theodik** [comment]
problém s metadaty zde #58
