### ISSUE TITLE
Cena ve srovnávači VS Realita

### ISSUE THREAD

**Issue by keivulan** [topmonks/hlidac-shopu#55]
Zdravím,

konkrétně tento produkt https://www.alza.cz/wd-red-6tb-d5655565.htm 
Nabídka srovnávače 5229 Kč > klik https://pevne-disky.heureka.cz/wd-6tb-3_5-sataiii-wd60efax/
Tam najdu cenu co našel vyhledávač klik do obchodu https://www.nc.cz/?cls=stoitem&stiid=378125
A tam je cena úplně jiná.

Je chyba u mě ? Nebo ten obchod propaguje na Heuréce jinou cenu, kterou ve finále ani nemá.

**Comment by theodik** [comment]
vedle :D
