### ISSUE TITLE
nakup.itesco.cz přestal zobazovat graf s cenou

### ISSUE THREAD

**Issue by JanCernyCZ** [topmonks/hlidac-shopu#57]
Hezký večer, na e-shopu Tesca se přestal zobrazovat graf s cenami. Začalo to před pár týdny, ale nejsem schopý říct od kdy. Zkoušeno jak v Chrome, tak FF. Na stránce www.hlidacshopu.cz se graf vygeneruje.

**Comment by theodik** [comment]
Díky, opraveno. Vyhodím to co nejdřív
