### ISSUE TITLE
Chyba v názvech souborů doplňku

### ISSUE THREAD

**Issue by lordrak007** [topmonks/hlidac-shopu#66]
Dobrý den,
prohlížeč po aktualizaci hlásí chybu:
Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

**Comment by theodik** [comment]
Na které stránce, nebo kdy a kde to hlásí tuhle chybu? Pomohl by přímo link kde se to děje.

**Comment by lordrak007** [comment]
Přímo v rozšíření prohlížeče, když se otevře nastavení doplňku.
Po dvou restartech počítače se to ale přestalo objevovat. Je možné, že to byla chyba samotného prohlížeče.
Děkuji

**Comment by theodik** [comment]
Ok fajn, kdyby se to opakovalo poprosil bych info kde se to děje, kdy, jaký prohlížeč a případně verzi, ať se mám od čeho odpíchnout :)
