### ISSUE TITLE
Výpočet reálné slevy

### ISSUE THREAD

**Issue by rarous** [topmonks/hlidac-shopu#69]
Je potřeba změnit metodiku proti čemu tu slevu počítáme. Maximum za posledních 90 dní je neoptimální. Musíme přejít na "histogram", tj. brát to proti hodnotě, za kterou se to za posledních 90 dní prodávalo nejčastěji. Přejdeme tím chybám se zdražováním na poslední chvíli před slevou (to maximum nevidí) a zároveň nám to bude ukazovat i reálné zdražení. To teď neumíme spočítat vůbec protože při zdražování je maximum včerejší hodnota a proti dnešní už je změna 0%.

**Comment by rarous** [comment]
Další možností je držet se metodiky EU, která bude muset být implementovaná během dvou let.
[factsheet_new_deal_consumer_benefits_2019.pdf](https://github.com/topmonks/hlidac-shopu/files/5083960/factsheet_new_deal_consumer_benefits_2019.pdf)

**Comment by jakubbalada** [comment]
Výpočet podle nové EU směrnice chápu následovně:
Při snížení prodejní ceny se jako referenční (přeštrknutá) cena nastaví nejnižší prodejní cena za posledních 30 dní před tímto snížením. Tato referenční cena se uvádí do dalšího snížení ceny (nepřepočítává se každý den, ale jen při "price reduction claim"). Případ následného zvýšení ceny se zatím nejspíš neřeší, referenční cenu bych v takovém případě neměnil.
Pokud budeme slevu vypočítávat každý den, je potřeba jít do historie a najít poslední zlevnění. Efektivnější asi bude si slevu persistovat a změnit v okamžiku zlevnění.
Přesně znění:
_For every price reduction claim, sellers will have to indicate as reference price the lowest price applied within a period of at least 30 days preceding the price reduction announcement._

**Comment by rarous** [comment]
Tady vidím jediný problém a to je ten announcement :)

**Comment by rarous** [comment]
Na webu už je nasazena verze, kdy se sleva počítá vůči nejnižší ceně za 30 před slevovou akcí. Po skončení slevové akce navrhuji držet se mého původního návrhu, tj. počítat slevu vůči nejčastější ceně za 90 dní před akcí.

**Comment by rarous** [comment]
Fixed in https://github.com/topmonks/hlidac-shopu/commit/57430a03a070993d9615024de355068378e63947
