### ISSUE TITLE
Doplněk mizel z nabídky pro Firedox

### ISSUE THREAD

**Issue by JanCernyCZ** [topmonks/hlidac-shopu#9]
Dobrý den,
Z jakého důvodu byl doplněk stažen z nabídky Firefoxu? Pro Chrome je stále k dispozici.
https://addons.mozilla.org/cs/firefox/addon/hlídač-shopů/
Díky za odpověď
Honza

**Comment by theodik** [comment]
Ahoj, ff nám odmítl novou verzi, už tam letí oprava tak snad bude fungovat co nevidět.

**Comment by JanCernyCZ** [comment]
Ahoj, díky za dobrou zprávu. Nakonec jsem ho vyhrabal z uživatelského profilu FF v druhém počítači.

**Comment by theodik** [comment]
dalo to zabrat, ale je tam 😂
https://addons.mozilla.org/en-US/firefox/addon/hl%C3%ADda%C4%8D-shop%C5%AF/
